### PR TITLE
Add maven pom file

### PR DESCRIPTION
**Pull request by tsmock**

### CODE REVIEW

**Comment by risicle** [comment]
Would you like to take over maintainership? I would find it hard to review/test this now and by the looks of it you've managed to make yourself more familiar with the code than I currently am..

**Comment by tsmock** [comment]
Kind of up to you. I'm not at all familiar with the markseen codebase; I am very familiar with the JOSM codebase and how the setup/teardown methods should be done in JUnit5.

If you do give me maintainership, I'll probably want to transfer the repo over to the [JOSM](https://github.com/JOSM) GitHub organization.

**Comment by risicle** [comment]
Well, I'm not sure how much maintenance the algorithmic bits of markseen will need. Luckily they seem to have mostly held up over the years with extremely little attention, and I see them as pretty solid. At its core, markseen is really an implementation of a quadtree-based multi-resolution bitmap, and I think I've quite heavily commented the "tricky" bits - though of course you could still call on me if help was needed there.

(As an aside, at one point I was going to reuse the multi-resolution bitmap from here in a second plugin that would allow arbitrary "painting" on the map and possibly support automatic conversion back and forth to area polygons..)

I'd have no problem at all with transferring the repo to the JOSM org.

**Comment by risicle** [comment]
It looks like I need permission to create repositories in JOSM before it'll let me transfer ownership of the repo.

**Comment by tsmock** [comment]
I _believe_ if I am set as a maintainer/owner I can move it. If not, @stoecker will have to do it.

**Comment by risicle** [comment]
I've managed to make you a "collaborator" but that might be the most access I can give you on a personal account.

**Comment by tsmock** [comment]
`Settings` -> `Transfer ownership` (to another user, specifically `tsmock` or `stoecker`) might be an option. I'd prefer to just transfer it directly to the JOSM org, but it it looks like that might not be possible.

From reading docs, it looks like there are only two permission groups for personal repos; owner and collaborator.

References:
* https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository
* https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/permission-levels-for-a-personal-account-repository

**Comment by risicle** [comment]
> tsmock/josm-markseen already exists

:grin:

**Comment by tsmock** [comment]
Fixed. 🍴

**Comment by risicle** [comment]
> tsmock already has a repository in the risicle/josm-markseen network

:grin: :grin:

**Comment by tsmock** [comment]
I've deleted by fork; the code for this PR lives on at https://github.com/risicle/josm-markseen/tree/pom .

**Comment by tsmock** [comment]
OK. `markseen` has been moved to the JOSM org. This was a PITA, mostly because I had a fork. You (@risicle ) should still have collaborator status and be able to make modifications to this repo. If you don't, I'll have to poke @stoecker since I don't have admin status for the JOSM organization.

**Comment by stoecker** [comment]
I can certainly do what you want if you tell me what. Thought I assumed you are admin...

**Comment by stoecker** [comment]
Hmm, did your status change?

**Comment by tsmock** [comment]
I don't think I've ever had admin status on the GitHub org. You might be thinking about a repo that is in the GitHub org, but I'm not certain on that.

I think I had admin status on sonar at one point, but I think that got removed on an update or something. It hasn't been super critical for me to make changes there, so I haven't poked you on it.

**Pull request closed without merging**
